marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
app_name = "product"


urlpatterns = [
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', views.cart_detail,name='cart_detail'),
    path("e-market/", views.EmarketView.as_view(), name="e-market"),

    path('add-product/', views.AddProductView.as_view(), name="add-product"),
    path('my-shop/', views.MyShopProductView.as_view(), name="my-shop"),
    path('update-product/', views.UpdateProductView.as_view(), name="update-product"),
    path('edit-product/<int:pk>', views.EditProductView.as_view(), name="edit-product"),
    path('delete-product/<int:pk>', views.DeleteProductView.as_view(), name="delete-product"),
    path('details-product/<int:pk>', views.DetailProductView.as_view(), name="details-product"),
    path('seller-contact/<int:pk>', views.SellerContactView.as_view(), name="seller-contact"),
    path("product-by-category/<int:pk>", views.ProductByCategory.as_view(), name="product-by-category"),
    path('order-submit', views.OrderSubmit.as_view(), name="order-submit"),
    path('product-search', views.ProductSearchView.as_view(), name="product-search"),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
# from django_private_chat import urls as django_private_chat_urls
from django.conf.urls.static import static
from django.conf import settings
from core import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firebase.urls')),
    path('user/', include('userprofile.urls')),
    path('post/', include('post.urls')),
    # url(r'^', include(django_private_chat_urls)),
    url('friendship/', include('userfollow.urls')),
    path('comment/', include('comment.urls')),
    path('group/', include('group.urls')),
    path('product/', include('marketplace.urls')),
    path('web/', include('web.urls')),
    path('blog/', include('blog.urls')),
    path('todo/', include('todo.urls')),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url('notification/', include('notifications.urls', 'notifications')),
    url('chat/', include('chat.urls')),
    url('advertise/', include('advertise.urls')),
    url('tools/', include('tools.urls')),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    path('channel/', include('chanel.urls')),


]
if urlpatterns:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

web/urls.py
from django.urls import path
from . import views
app_name = "web"

urlpatterns = [

]

marketplace/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now


class Category(models.Model):
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='products/', null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=255, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(null=True, default=now)

    def __str__(self):
        return self.name


class Order(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField(null=True, blank=True)
    status = models.CharField(max_length=255, blank=True, null=True)
    user_id = models.IntegerField(null=True, blank=True)
    qty = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, default=now)

    def __str__(self):
        return self.name


class ProductSlider(models.Model):
    name = models.CharField(max_length=255, null=True)
    image = models.ImageField(upload_to='sliders/', null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(null=True, default=now)

    def __str__(self):
        return self.name

marketplace/forms.py
from django import forms
from .models import Category, Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'name','image','description','price','category'
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Product name'}),
            'price': forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Product Price'}),
            # 'category': forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Product Price'}),
            'description': forms.Textarea(attrs={'class' : 'form-control','rows':'3'}),
        }

marketplace/views.py
import os

from django.contrib import messages
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View
from .forms import ProductForm
from .models import Product, Order, Category, ProductSlider
from django.contrib.auth.decorators import login_required
from cart.cart import Cart


@login_required(login_url="/")
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("product:e-market")


@login_required(login_url="/")
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("product:cart_detail")


@login_required(login_url="/")
def item_increment(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("product:cart_detail")


@login_required(login_url="/")
def item_decrement(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("product:cart_detail")


@login_required(login_url="/")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("product:cart_detail")


@login_required(login_url="/")
def cart_detail(request):
    return render(request, 'product/cart_details.html')


class EmarketView(View):
    def get(self, request):
        products = Product.objects.filter().order_by('-id')
        categories = Category.objects.filter()
        sliders = ProductSlider.objects.all()
        context = {
            'products': products,
            'categories': categories,
            'sliders': sliders
        }
        return render(request, 'product/e_market.html', context)


class ProductByCategory(View):
    def get(self, request, pk):
        products = Product.objects.filter(category_id=pk).order_by('-id')
        # categories = Category.objects.filter().order_by('-id')
        context = {
            'products': products,
            # 'categories': categories
        }
        return render(request, 'product/product_by_cat.html', context)

#
# To view the cart detail page use the below code
#
# {% load cart_tag %}
#
# Total Length :: {{request.session.cart|length}}
#
# Cart Detail:
#
# {% for key,value in request.session.cart.items %}
# {{value.name}} {{value.price}} {{value.quantity}} {{value.image}} Total {{ value.price|multiply:value.quantity }}
#
# {% endfor %}


class AddProductView(View):
    def get(self, request):
        form = ProductForm()
        context = {
            'status': 'active',
            'form': form,
        }
        return render(request, 'product/add_product.html', context)

    def post(self, request):
        form = ProductForm(request.POST or None, request.FILES or None)
        if request.method == 'POST':

            if form.is_valid():
                obj = form.save(commit=False)
                obj.user = request.user;
                obj.save()
                form = ProductForm()
                messages.success(request, "Successfully created")

        return render(request, 'product/add_product.html', {'form': form})


class MyShopProductView(View):
    def get(self, request):
        products = Product.objects.filter(user_id=request.user.id)
        context = {
            'products': products
        }
        return render(request, 'product/my_shop.html', context)


class EditProductView(View):
    def get(self, request, pk):
        data = Product.objects.get(pk=pk)
        form = ProductForm(instance=data)
        context = {
            'sttus': 'active',
            'data': data,
            'form': form,
            'id': data.id,
        }
        return render(request, 'product/edit.html', context)


class UpdateProductView(View):
    def post(self, request):
        id = request.POST.get('id')
        product = Product.objects.get(id=id)
        form = ProductForm(request.POST, request.FILES or None, instance=product)
        context = {
            'status': 'active',
            'form': form,
        }
        if form.is_valid():
            form.save()
            messages.success(request, 'Data updated successful', extra_tags='success')
        else:
            return render(request, 'product/edit.html', context)
        return redirect('product:my-shop')


class DeleteProductView(View):
    def get(self, request, pk):
        id = request.POST.get('id')
        product = Product.objects.get(id=pk)
        product.delete()
        messages.success(request, 'Data updated successful', extra_tags='success')
        return redirect('product:my-shop')


class DetailProductView(View):
    def get(self, request, pk):
        product = Product.objects.get(id=pk)
        user = User.objects.get(pk=product.user_id)

        context = {
            'product': product,
            'user': user
        }
        return render(request, 'product/product_details.html', context)


class SellerContactView(View):
    def get(self, request, pk):

        return render(request, 'product/seller_contact.html')


class OrderSubmit(View):
    def post(self, request):
        name = request.POST.getlist('name[]')
        price = request.POST.getlist('price[]')
        qty = request.POST.getlist('qty[]')
        subtotal = request.POST.get('subtotal')

        datalen = len(name)
        i = 0
        while i < datalen:
            data = Order()
            data.name = name[i]
            data.price = price[i]
            data.qty = qty[i]
            data.user_id = request.user.id
            data.status = 1
            data.save()
            i += 1
        cart = Cart(request)
        cart.clear()
        response = {
            'success': 'Success! '
        }
        return JsonResponse(response)


class ProductSearchView(View):
    def post(self, request):
        name = request.POST.get('name')
        products = Product.objects.filter(name=name)
        context = {
            'products': products
        }
        return render(request, 'product/product_search.html', context)

marketplace/templates/product/add_product.html
{% extends 'front/base.html' %}
{% block title %} Konetos | E-Market {% endblock %}
{% block content %}
{% load static %}
<div class="container" style="margin-top: 150px;">
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <p  {% if message.tags %} class="text-success" {% endif %}> {{ message }} </p>
    {% endfor %}
</ul>
{% endif %}

    <form action="{% url 'product:add-product' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">{{ form.name.label }}</label>
      {{ form.name }}
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">{{ form.price.label }}</label>
      {{ form.price }}
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">{{ form.description.label }} </label>
    {{ form.description }}
  </div>
         <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputAddress2">{{ form.image.label }}</label>
            {{ form.image }}
          </div>
                <div class="form-group col-md-6">
            <label for="inputAddress2">{{ form.category.label }}</label>
            {{ form.category }}
          </div>
         </div>
         <button type="submit" class="btn btn-info">Add Product</button>
</form>
</div>

{% endblock content %}

marketplace/templates/product/cart_details.html
{% extends 'front/base.html' %}
{% block title %} Konetos | E-Market {% endblock %}
{% block content %}
{% load static %}
{% load cart_tag %}
 <div id="content-page" class="content-page">
            <div class="container">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="iq-card">
                        <div class="iq-card-body">
                           <div class="row">
                            <p class="text-success" id="final_msg"> Order submited.</p>
                              <div class="col-sm-12">
                                 <h5>Order Summary</h5>
                                 <div class="table-responsive-sm">
                                  <form id="orderform" action="" method="POST" >
                                  {% csrf_token %}
                              
                                    <table class="table table-striped" id="tableData">
                                       <thead>
                                          <tr  data-param1="0">
                                             <th class="text-center" scope="col">#</th>
                                             <th scope="col">Item</th>
                                             <th scope="col">Image</th>
                                             <th class="text-center" scope="col">Quantity</th>
                                             <th class="text-center" scope="col">Price</th>
                                             <th class="text-center" scope="col">Totals</th>
                                          </tr>
                                       </thead>
                                       <tbody>
                                       {% for key,value in request.session.cart.items %}
                                          <tr data-param1="{{ value.price|multiply:value.quantity }}">
                                             <td class="text-center" scope="row">{{ forloop.counter }}</td>
                                             <td>
                                                <h6 class="mb-0">{{value.name}}</h6>
                                             </td>
                                              <td>
                                                <h6 class="mb-0"><img src="{{value.image}}" style="height: 50px; width: 50px;" alt=""></h6>
                                             </td>
                                             <td class="text-center">{{value.quantity}} </td>
                                             <td class="text-center">{{value.price}}</td>
                                             <td class="text-center"><b>{{ value.price|multiply:value.quantity }}</b></td>
                                          </tr>
                                       <input type="hidden" name="name[]" value="{{value.name}}">
                                       <input type="hidden" name="price[]" value="{{value.price}}">
                                       <input type="hidden" name="qty[]" value="{{value.quantity}}">

                                          <input id="total_price" type="hidden" value="" name="subtotal">

                                       {% endfor %}
                                       
                                       </tbody>
                                    </table>
                                    <table class="table table-striped">
                                       <tbody>
                                          <tr>
                                             <td></td>
                                             <td></td>
                                             <td></td>
                                             <td></td>
                                             <td></td>
                                             <td></td>
                                             <td></td>
                                             <td>SubTotal</td>
                                             <td id="total"><b></b></td>
                                          </tr>
                                       </tbody>
                                    </table>
                                      <div class="col-md-12 text-right">
                                 <button type="button" class="btn btn-link mr-3"><i class="ri-printer-line"></i> Download Print</button>
                                 <button type="submit" class="btn btn-dark pull-right">Submit</button>
                              </div>
                                  </form>
                                 </div>
                              </div>
                              <div class="col-sm-6"></div>

                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script>

$(document).ready(function(){
    var TotalValue = 0;
    var id =$(this).data('value');
    
    var TotalValue = 0;
    $("#tableData tr").each(function(){

          var param1 = $(this).data('param1');
          TotalValue += parseFloat(param1);
          
    });
     $("#total").text(TotalValue);
     $("#total_price").val(TotalValue);
    
});
</script>

<script>
   /// post
$('#orderform').submit(function(e){
        e.preventDefault();

        $form = $(this);
        var formData = new FormData(this);


        $.ajax({
            url: "{% url 'product:order-submit' %}",
            type: 'POST',
            data: formData,
            success: function (data) {
              Swal.fire('Your order has been submited!')

               window.setTimeout(function() {
                    window.location.href = '{% url 'product:e-market' %}';
                }, 2000);
            },
            cache: false,
            contentType: false,
            processData: false

        });
    });
/// post

</script>
{% endblock content %}

marketplace/templates/product/edit.html
{% extends 'front/base.html' %}
{% block title %} Konetos | E-Market {% endblock %}
{% block content %}
{% load static %}
<div class="container" style="margin-top: 150px;">
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <p  {% if message.tags %} class="text-success" {% endif %}> {{ message }} </p>
    {% endfor %}
</ul>
{% endif %}

    <form action="{% url 'product:update-product' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{id}}">
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">{{ form.name.label }}</label>
      {{ form.name }}
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">{{ form.price.label }}</label>
      {{ form.price }}
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">{{ form.description.label }} </label>
    {{ form.description }}
  </div>
         <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputAddress2">{{ form.image.label }}</label>
            {{ form.image }}
          </div>
                <div class="form-group col-md-6">
            <label for="inputAddress2">{{ form.category.label }}</label>
            {{ form.category }}
          </div>
         </div>
         <button type="submit" class="btn btn-info">Update Product</button>
</form>
</div>

{% endblock content %}

marketplace/templates/product/menu.html
               <div class="row">
                  <div class="col-lg-12 my-2">
                     <ul class="nav nav-pills d-flex align-items-center justify-content-center profile-feed-items p-0 m-0">
                        <li class="col-sm-3 p-0">
                           <a class="nav-link active m-2" style="background-color: #27b6b6; color: white;" href="{% url 'product:add-product' %}">Add Product</a>
                        </li>
                        <li class="col-sm-3 p-0">
                           <a class="nav-link m-2" style="background-color: #27b6b6; color: white;" href="{% url 'product:my-shop' %}">My Shop</a>
                        </li>
                        <li class="col-sm-3 p-0">
                           <a class="nav-link m-2" style="background-color: #27b6b6; color: white;" href="my_sellers.html">My Sellers</a>
                        </li>
                        <li class="col-sm-3 p-0">
                           <a class="nav-link m-2" style="background-color: #27b6b6; color: white;" href="add_new_ad.html">Add New Ad</a>
                        </li>
                     </ul>
                  </div>
               </div>

marketplace/templates/product/my_shop.html
{% extends 'front/base.html' %}
{% block title %} Konetos | E-Market {% endblock %}
{% block content %}
{% load static %}
 <div id="content-page" class="content-page">
            <div class="container-fluid">

            </div>
            <div class="container-fluid mt-4">
               <div class="header-for-bg mb-4 mt-2">
                  <div class="background-header position-relative">
                     <img src="{% static 'images/page-img/profile-bg1.jpg' %} " class="img-fluid w-100 rounded rounded" alt="header-bg">
                     <div class="title-on-header w-75 mx-auto">

                  </div>
               </div>
               <h1></h1>
               <div class="row">
                  {%  for product in products %}
                  <div class="col-sm-12 col-md-4 col-lg-3">
                     <div class="iq-card">
                        <div class="top-bg-image">
                           <img src="{{ product.image.url }} " style="height: 200px;" class="img-fluid w-100" alt="group-bg">
                        </div>
                        <div class="iq-card-body text-center">
                           <div class="group-info">
                              <h4 style="display: inline-block">{{ product.name |truncatechars:20 }}</h4>
                              <p>{{ product.category }}</p>
                           </div>
                           <div class="group-details d-inline-block">
                              <ul class="d-flex align-items-center justify-content-between list-inline m-0 p-0">
                                 <li class="pl-1 pr-1">
                                    <p class="mb-0">Price</p>
                                    <h6>${{ product.price }}</h6>
                                 </li>
                                 <li class="pl-1 pr-1">
                                    <p class="mb-0">Visit</p>
                                    <h6>1.2k</h6>
                                 </li>
                              </ul>
                           </div>
                           <a class="nav-link" style="background-color: #27b6b6; color: white;" href="{% url 'product:edit-product' product.id %}">Edit</a>
                            <a class="nav-link mt-2" style="background-color: red; color: white;" onclick="return confirm(' you want to delete?');" href="{% url 'product:delete-product' product.id %}">Delete</a>
                        </div>
                     </div>
                  </div>
                 {% endfor %}
               </div>
            </div>

             </div>
 </div>

{% endblock content %}

marketplace/templates/product/product_by_cat.html
{% extends 'front/base.html' %}
{% block title %} Konetos | E-Market {% endblock %}
{% block content %}
{% load static %}
 <div id="content-page" class="content-page">
            <div class="container-fluid">

            </div>
            <div class="container-fluid mt-4">
               <div class="header-for-bg mb-4 mt-2">
                  <div class="background-header position-relative">
                     <img src="{% static 'images/page-img/profile-bg1.jpg' %} " class="img-fluid w-100 rounded rounded" alt="header-bg">
                     <div class="title-on-header w-75 mx-auto">
                  </div>
               </div>
               <h1></h1>
               <div class="row">
                  {%  for product in products %}
                  <div class="col-sm-12 col-md-4 col-lg-3">
                     <div class="iq-card">
                        <div class="top-bg-image">
                           <img src="{{ product.image.url }} " style="height: 200px;" class="img-fluid w-100" alt="group-bg">
                        </div>
                        <div class="iq-card-body text-center">
                           <div class="group-info">
                              <h4 style="display: inline-block">{{ product.name |truncatechars:20 }}</h4>
                              <p>{{ product.category }}</p>
                           </div>
                           <div class="group-details d-inline-block">
                              <ul class="d-flex align-items-center justify-content-between list-inline m-0 p-0">
                                 <li class="pl-1 pr-1">
                                    <p class="mb-0">Price</p>
                                    <h6>${{ product.price }}</h6>
                                 </li>
                                 <li class="pl-1 pr-1">
                                    <p class="mb-0">Visit</p>
                                    <h6>1.2k</h6>
                                 </li>
                              </ul>
                           </div>
                          <a class="nav-link" style="background-color: #27b6b6; color: white;" href="{% url 'product:seller-contact' product.user_id %}">Contact</a>
                           <a class="nav-link mt-2" style="background-color: #27b6b6; color: white;" href="{% url 'product:cart_add' product.id %}">Buy</a>
                       </div>
                     </div>
                  </div>
                 {% endfor %}
               </div>
            </div>

             </div>
 </div>

{% endblock content %}

marketplace/templates/product/product_details.html
{% extends 'front/base.html' %}
{% block title %} Konetos | E-Market {% endblock %}
{% block content %}
{% load static %}
<div id="content-page" class="content-page">
            <div class="container-fluid">
                {% include 'product/menu.html' %}
               <div class="row">
                  <!-- The sidebar -->
                  <div class="col-lg-3">
                     <h1 class="text-center mt-4" style="color: #27b6b6;">Price {{ product.price}}</h1>
                     <h3 class="text-center mt-4" style="color: #27b6b6;">Date Listed</h3>
                     <h4 class="text-center" style="color: #27b6b6;">{{ product.created_at}}</h4>
                     <br><br><br><br><br><br>
                     <h3 class="text-center mt-4" style="color: #27b6b6;">Product Seller</h3>
                     <h4 class="text-center" style="color: #27b6b6;">{{ user.username }}</h4>
                  </div>

                  <!-- Page content -->
                  <div class="col-lg-9">
                     <img src="{{ product.image.url }}" alt="Los Angeles" width="900" height="500">
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-12">
                     <h1  class="text-center mt-4" style="color: #27b6b6;">Description</h1>
                     <p class="lead font-weight-bold mt-4">
                        {{ product.description }}
                     </p>
                  </div>
               </div>
            </div>

         </div>
{% endblock content %}

marketplace/templates/product/product_search.html
{% extends 'front/base.html' %}
{% block title %} Konetos | E-Market {% endblock %}
{% block content %}
{% load static %}
 <div id="content-page" class="content-page">
     <div class="container-fluid mt-4">
               <div class="header-for-bg mb-4 mt-2">
                  <div class="background-header position-relative">
                     <img src="{% static 'images/page-img/profile-bg1.jpg' %} " class="img-fluid w-100 rounded rounded" alt="header-bg">
                     <div class="title-on-header w-75 mx-auto">
                  </div>
               </div>
               <h1></h1>
               <div class="row">
                  {%  for product in products %}
                  <div class="col-sm-12 col-md-4 col-lg-3">
                     <div class="iq-card">
                        <div class="top-bg-image">
                           <img src="{{ product.image.url }} " style="height: 200px;" class="img-fluid w-100" alt="group-bg">
                        </div>
                        <div class="iq-card-body text-center">
                           <div class="group-info">
                              <h4 style="display: inline-block">{{ product.name |truncatechars:20 }}</h4>
                              <p>{{ product.category }}</p>
                           </div>
                           <div class="group-details d-inline-block">
                              <ul class="d-flex align-items-center justify-content-between list-inline m-0 p-0">
                                 <li class="pl-1 pr-1">
                                    <p class="mb-0">Price</p>
                                    <h6>${{ product.price }}</h6>
                                 </li>
                                 <li class="pl-1 pr-1">
                                    <p class="mb-0">Visit</p>
                                    <h6>1.2k</h6>
                                 </li>
                              </ul>
                           </div>
                          <a class="nav-link" style="background-color: #27b6b6; color: white;" href="{% url 'product:seller-contact' product.user_id %}">Contact</a>
                           <a class="nav-link mt-2" style="background-color: #27b6b6; color: white;" href="{% url 'product:cart_add' product.id %}">Buy</a>
                       </div>
                     </div>
                  </div>
                 {% endfor %}
               </div>
            </div>
        </div>
 </div>

{% endblock content %}