social/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
# from django_private_chat import urls as django_private_chat_urls
from django.conf.urls.static import static
from django.conf import settings
from core import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firebase.urls')),
    path('user/', include('userprofile.urls')),
    path('post/', include('post.urls')),
    # url(r'^', include(django_private_chat_urls)),
    url('friendship/', include('userfollow.urls')),
    path('comment/', include('comment.urls')),
    path('group/', include('group.urls')),
    path('product/', include('marketplace.urls')),
    path('web/', include('web.urls')),
    path('blog/', include('blog.urls')),
    path('todo/', include('todo.urls')),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url('notification/', include('notifications.urls', 'notifications')),
    url('chat/', include('chat.urls')),
    url('advertise/', include('advertise.urls')),
    url('tools/', include('tools.urls')),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    path('channel/', include('chanel.urls')),


]
if urlpatterns:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

userprofile/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name = "user"

urlpatterns = [

    path('profile/', views.ProfileView.as_view(), name="profile"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("contact-information-create", views.ContactInformationView.as_view(), name="contact-information-create"),
    path("detail-information-create", views.DetailInformationView.as_view(), name="detail-information-create"),
    path("get-contact-information/<int:user_id>", views.GetContactinfoView.as_view(), name="get-contact-information"),
    path("get-details-information/<int:user_id>", views.GetDetailsinfoView.as_view(), name="get-details-information"),
    path("place-information-create", views.PlaceCreteView.as_view(), name="place-information-create"),
    path("get-place-information/<int:user_id>", views.GetPlaceinfoView.as_view(), name="get-place-information"),
    path("relation-information-create", views.RelationCreateView.as_view(), name="relation-information-create"),
    path("get-relation-information/<int:user_id>", views.GetRelationinfoView.as_view(), name="get-relation-information"),
    path("work-information-create", views.WorkCreateView.as_view(), name="work-information-create"),
    path("get-company-information/<int:user_id>", views.GetCompanyinfoView.as_view(), name="get-company-information"),
    path("get-education-information/<int:user_id>", views.GetEducationInfoView.as_view(), name="get-education-information"),
    path("education-information-create", views.CreateEducationView.as_view(), name="education-information-create"),
    path("profile-image-create", views.CreateProfileImageView.as_view(), name="profile-image-create"),
    path("cover-image-create", views.CreateCoverImageView.as_view(), name="cover-image-create"),
    path("search", views.SearchUserView.as_view(), name="search"),
    path("news-feed", views.NewsFeedView.as_view(), name="news-feed"),
    path("profile-image", views.ProfileImageView.as_view(), name="profile-image"),
    path("profile-video", views.ProfileVideoView.as_view(), name="profile-video"),
    path("profile-image-delete/<int:pk>", views.ProfileImageDeleteView.as_view(), name="profile-image-delete"),
    path("profile-video-delete/<int:pk>", views.ProfileVideoDeleteView.as_view(), name="profile-video-delete"),
    path('send-friend-request', views.FriendRequestSendView.as_view(), name="send-friend-request"),
    path('user-friend-request', views.UserFriendRequest.as_view(), name="user-friend-request"),
    path('cancel-request/<int:pk>', views.CancelFriendRequestView.as_view(), name="cancel-request"),
    path('delete-request/<int:pk>', views.DeleteFriendRequestView.as_view(), name="delete-request"),
    path('confirm-request/<int:pk>', views.ConfirmFriendRequestView.as_view(), name="confirm-request"),
    path('user-birthday', views.UserBirthdayView.as_view(), name="user-birthday"),
    # path('calender', views.CalenderView.as_view(), name="calender"),

    path('events/', views.calendar, name='events'),
    path('add_event/', views.add_event, name='add_event'),
    path('update_event/', views.update_event, name='update_event'),
    path('edit-event/<int:pk>', views.edit, name='edit-event'),
    path('delete-event/<int:pk>', views.remove, name='delete-event'),

    path('work-remove/<int:pk>', views.WorkRemoveView.as_view(), name="work-remove"),
    path('education-remove/<int:pk>', views.EducationRemoveView.as_view(), name="education-remove"),
    path('education-edit/<int:pk>', views.EducationEditView.as_view(), name="education-edit"),
    path('work-edit/<int:pk>', views.WorkEditView.as_view(), name="work-edit"),

    path("account-setting/", views.AccountSettingView.as_view(), name="account-setting"),
    path("privacy-setting/", views.PrivacySettingView.as_view(), name="privacy-setting"),
    path("update_server/", views.update, name="update"),


]

web/urls.py
from django.urls import path
from . import views
app_name = "web"

urlpatterns = [

]

userprofile/views.py
from django.conf.global_settings import LOGIN_REDIRECT_URL
from django.contrib import messages, auth
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import serializers
from django.core.serializers import json
from django.db.models import Count
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Contact, Details, Address, Relation, Work, Education, ProfileImage, Events
# Create your views here.
from django.utils.decorators import method_decorator
from django.views import View
from post.models import Post, Photo, Following, Video, PostComment
from django.db.models import Q
# from groups_manager.models import Group, Member
from notify.signals import notify
from dateutil import parser
import git
from django.views.decorators.csrf import csrf_exempt


class ProfileView(View):
    @method_decorator(login_required)
    def get(self, request):
        post = Post.objects.filter(user_id=request.user.id)
        total_post = post.aggregate(total_count=Count('id'))

        try:
            profile = ProfileImage.objects.get(user_id=request.user.id)
        except ProfileImage.DoesNotExist:
            profile = ""

        posts = Post.objects.filter(user_id=request.user.id, status=1).order_by('-id')

        photo = Photo.objects.filter(user_id=request.user.id).order_by('-id')
        following = Following.objects.filter(user_id=request.user.id).aggregate(total_following=Count('id'))
        total_follower = Following.objects.filter(following_id=request.user.id, status=2).aggregate(total_follower=Count('id'))
        work = Work.objects.filter(user_id=request.user.id)
        education = Education.objects.filter(user_id=request.user.id)
        all_fol = Following.objects.filter(following_id=request.user.id)
        id = request.user.id
        all_followers = []
        for value in all_fol:
            all_followers += User.objects.filter(pk=value.user_id)
        print(all_followers)


        context = {
            'total_post': total_post,
            'profile': profile,
            'photos': photo,
            'following': following,
            'total_follower': total_follower,
            'all_followers': all_followers,
            'userid': id,
            'posts': posts,
            'works': work,
            'educations': education
        }
        return render(request, 'profile/profile.html', context)


class LogoutView(View):
    @method_decorator(login_required)
    def get(self,request):
        auth.logout(request)
        messages.info(request, "Logged out successfully!")
        return redirect("/")


class ContactInformationView(View):
    @method_decorator(login_required)
    def post(self, request):
        if self.request.POST:
            username = request.POST.get('username')
            email = request.POST.get('email')
            phone = request.POST.get('phone')
            address = request.POST.get('address')
            website = request.POST.get('website')
            social = request.POST.get('social')
            birthday = request.POST.get('dob')
            language = request.POST.get('language')
            interest = request.POST.get('interest')
            gender = request.POST.get('gender')
            user_id = request.POST.get('user_id')

            data = Contact.objects.filter(
                user_id=user_id
            )
            cdata = len(data)

            if(cdata > 0):
                upd = Contact.objects.get(user_id=user_id)
                upd.username = username
                upd.email = email
                upd.mobile = phone
                upd.address = address
                upd.website = website
                upd.social_link = social
                upd.birthday = birthday
                upd.language = language
                upd.interest = interest
                upd.gender = gender
                upd.user_id = user_id
                upd.save()
                response = {
                    'success': 'Success!'
                }
            else:
                Contact.objects.create(
                    username=username,
                    email=email,
                    mobile=phone,
                    address=address,
                    website=website,
                    social_link=social,
                    birthday=birthday,
                    gender=gender,
                    language=language,
                    interest=interest,
                    user_id=user_id
                                       )
                response = {
                    'success': 'Success!'
                }
        else:
            response = {
                'error': 'something went wrong!'
            }
        return JsonResponse(response)



class DetailInformationView(View):
    @method_decorator(login_required)
    def post(self, request):
        if self.request.POST:
            name = request.POST.get('nick_name')
            about = request.POST.get('about')
            quote = request.POST.get('quote')
            user_id = request.POST.get('user_id')

            data = Details.objects.filter(
                user_id=user_id
            )
            cdata = len(data)

            if(cdata > 0):
                upd = Details.objects.get(user_id=user_id)
                upd.name = name
                upd.about = about
                upd.quote = quote
                upd.user_id = user_id
                upd.save()
                response = {
                    'success': 'Success!'
                }
            else:
                Details.objects.create(
                    name=name,
                    about=about,
                    quote=quote,
                    user_id=user_id
                                       )
                response = {
                    'success': 'Success!'
                }
        else:
            response = {
                'error': 'something went wrong!'
            }
        return JsonResponse(response)



class PlaceCreteView(View):
    @method_decorator(login_required)
    def post(self, request):
        if self.request.POST:
            lived = request.POST.get('lived')
            current_city = request.POST.get('current_city')
            user_id = request.POST.get('user_id')

            data = Address.objects.filter(
                user_id=user_id
            )
            cdata = len(data)

            if(cdata > 0):
                upd = Address.objects.get(user_id=user_id)
                upd.lived = lived
                upd.current_city = current_city
                upd.user_id = user_id
                upd.save()
                response = {
                    'success': 'Success!'
                }
            else:
                Address.objects.create(
                    lived=lived,
                    current_city=current_city,
                    user_id=user_id
                                       )
                response = {
                    'success': 'Success!'
                }
        else:
            response = {
                'error': 'something went wrong!'
            }
        return JsonResponse(response)


class RelationCreateView(View):
    @method_decorator(login_required)
    def post(self, request):
        if self.request.POST:
            status = request.POST.get('status')
            relation = request.POST.get('relation')
            member = request.POST.get('member')
            user_id = request.POST.get('user_id')

            data = Relation.objects.filter(
                user_id=user_id
            )
            cdata = len(data)

            if(cdata > 0):
                upd = Relation.objects.get(user_id=user_id)
                upd.status = status
                upd.relation = relation
                upd.user_id = user_id
                upd.member_id = member
                upd.save()
                response = {
                    'success': 'Success!'
                }
            else:
                Relation.objects.create(
                    status=status,
                    relation=relation,
                    member_id=member,
                    user_id=user_id
                                       )
                response = {
                    'success': 'Success!'
                }
        else:
            response = {
                'error': 'something went wrong!'
            }
        return JsonResponse(response)


class WorkCreateView(View):
    @method_decorator(login_required)
    def post(self, request):
        if self.request.POST:
            company = request.POST.get('company')
            designation = request.POST.get('designation')
            user_id = request.POST.get('user_id')

            Work.objects.create(
                company=company,
                designation=designation,
                user_id=user_id
            )
            response = {
                'success': 200
            }
            return redirect('user:profile')

        else:
            response = {
                'error': 'something went wrong!'
            }
        return JsonResponse(response)


class CreateEducationView(View):
    @method_decorator(login_required)
    def post(self, request):
        if self.request.POST:
            college = request.POST.get('college')
            location = request.POST.get('location')
            user_id = request.POST.get('user_id')

            data = Education.objects.filter(
                user_id=user_id
            )
            cdata = len(data)

            if(cdata > 0):
                upd = Education.objects.get(user_id=user_id)
                upd.college = college
                upd.location = location
                upd.user_id = user_id
                upd.save()
                response = {

userprofile/templates/profile/contactinfomodal.html
<!-- Modal -->
{% load static %}
<style>
    .modal-dialog {
    margin-top: 25%;
}

</style>
<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Contact Information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="" method="post" id="contactform">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">
                            <input type="text" id="oldusername" name="username" class="form-control" placeholder="username">
                        </div>
                        <div class="col">
                            <input type="text"  id="oldemail" name="email" class="form-control" placeholder="Email">
                        </div>

                    </div>
                    <div class="row">
                        <div class="col">
                            <input type="text" id="oldphone" name="phone" class="form-control" placeholder="Mobile">
                        </div>
                        <div class="col">
                            <input type="text" id="oldaddress" name="address" class="form-control" placeholder="Address">
                        </div>
                    </div>

                    <div class="row">

                        <div class="col">
                            <input type="text" id="oldwebsite" name="website" class="form-control" placeholder="Website">
                        </div>
                        <div class="col">
                            <input type="text" id="oldsocial" name="social" class="form-control" placeholder="Social Link">
                        </div>
                    </div>
                    <div class="row">

                        <div class="col">
                            <input type="date" id="olddob" name="dob" class="form-control" placeholder="Date of Birth">
                        </div>
                        <div class="col">
                            <select id="inputState" name="gender" class="form-control">
                                <option selected>Choose Gender...</option>
                                <option value="male">Male</option>
                                <option value="female">FeMale</option>
                                <option value="others">Others</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">

                        <div class="col">
                            <input type="text" id="oldlanguage" name="language" class="form-control" placeholder="Language">
                        </div>
                        <div class="col">
                            <input type="text" id="oldinterest" name="interest" class="form-control" placeholder="Interest">
                        </div>
                    </div>

                    <div class="row">

                        <input type="hidden" name="user_id" value="{{ user.id }}">

                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Save changes</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script>
   /// post
$('#contactform').submit(function(e){
        e.preventDefault();

        $form = $(this);
        var formData = new FormData(this);

        $.ajax({
            url: "{% url 'user:contact-information-create' %}",
            type: 'POST',
            data: formData,
            success: function (data) {
                fetchData();
                $('#contactModal').modal('hide');
            },
            cache: false,
            contentType: false,
            processData: false

        });
    });
 function fetchData() {
 var id = "{{ user.id }}"
    $.ajax({
            type: 'GET',
            url: "/user/get-contact-information/"+id,
            success:function(data){

             $('#username').text(data[0]['username']);
             $('#email').text(data[0]['email']);
             $('#mobile').text(data[0]['mobile']);
             $('#address').text(data[0]['address']);
             $('#website').text(data[0]['website']);
             $('#social').text(data[0]['social_link']);
             $('#birthday').text(data[0]['birthday']);
             $('#gender').text(data[0]['gender']);
             $('#language').text(data[0]['language']);
             $('#interest').text(data[0]['interest']);

             $('#oldusername').val(data[0]['username']);
             $('#oldemail').val(data[0]['email']);
             $('#oldmobile').val(data[0]['mobile']);
             $('#oldaddress').val(data[0]['address']);
             $('#oldwebsite').val(data[0]['website']);
             $('#oldsocial').val(data[0]['social_link']);
             $('#olddob').val(data[0]['birthday']);
             $('#oldgender').val(data[0]['gender']);
             $('#oldlanguage').val(data[0]['language']);
             $('#oldinterest').val(data[0]['interest']);
            }
        });

};
/// post



</script>

<script>
$(document).ready(function(){
   fetchData();

});

</script>

userprofile/templates/profile/cover.html
<!-- Modal -->
{% load static %}
<style>
    .modal-dialog {
    margin-top: 25%;
}

</style>
<div class="modal fade" id="coverModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Place You Lived</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="" method="post" id="coverform" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">
                            <input type="file" name="cover" class="form-control" placeholder="company">
                        </div>

                    </div>

                    <div class="row">

                        <input type="hidden" name="user_id" value="{{ user.id }}">

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Save changes</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script>
   /// post
$('#coverform').submit(function(e){
        e.preventDefault();

        $form = $(this);
        var formData = new FormData(this);

        $.ajax({
            url: "{% url 'user:cover-image-create' %}",
            type: 'POST',
            data: formData,
            success: function (data) {

                $('#coverModal').modal('hide');
            },
            cache: false,
            contentType: false,
            processData: false

        });
    });
/// post

</script>

userprofile/templates/profile/details.html
<!-- Modal -->
{% load static %}
<style>
    .modal-dialog {
    margin-top: 25%;
}

</style>
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Details Information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="" method="post" id="detailsform">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">
                            <input type="text" name="about" id="oldabout" class="form-control" placeholder="about">
                        </div>
                        <div class="col">
                            <input type="text" id="oldname" name="nick_name" class="form-control" placeholder="Nick Name">
                        </div>

                    </div>
                    <div class="row">
                        <div class="col">
                            <textarea id="oldquote" name="quote" class="form-control" cols="30" rows="5">type here</textarea>
                        </div>

                    </div>

                    <div class="row">

                        <input type="hidden" name="user_id" value="{{ user.id }}">

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Save changes</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script>
   /// post
$('#detailsform').submit(function(e){
        e.preventDefault();

        $form = $(this);
        var formData = new FormData(this);

        $.ajax({
            url: "{% url 'user:detail-information-create' %}",
            type: 'POST',
            data: formData,
            success: function (data) {
                fetchDetailData();
                $('#detailModal').modal('hide');
            },
            cache: false,
            contentType: false,
            processData: false

        });
    });
 function fetchDetailData() {
 var id = "{{ user.id }}"
    $.ajax({
            type: 'GET',
            url: "/user/get-details-information/"+id,
            success:function(data){

             $('#name').text(data[0]['name']);
             $('#oldname').val(data[0]['name']);
             $('#detailabout').text(data[0]['about']);
             $('#oldabout').val(data[0]['about']);
             $('#quote').text(data[0]['quote']);
             $('#oldquote').val(data[0]['quote']);


            }
        });

};
/// post



</script>

<script>
$(document).ready(function(){
   fetchDetailData();

});

</script>

userprofile/templates/profile/friend_request_list.html
{% extends 'front/base.html' %}
{% block content %}
{% load static %}
{% load product_tags %}
 <div id="content-page" class="content-page">
            <div class="container">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="iq-card">
                        <div class="iq-card-header d-flex justify-content-between">
                           <div class="iq-header-title">
                              <h4 class="card-title">Friend Request</h4>
                           </div>
                        </div>
                        <div class="iq-card-body">
                           <ul class="request-list list-inline m-0 p-0">
                               {% for value in data %}
                              <li class="d-flex align-items-center">
                                 <div class="user-img img-fluid"><img src="/media/{% user_image value.user_id %}" alt="story-img" class="rounded-circle avatar-40"></div>
                                 <div class="media-support-info ml-3">
                                    <h6>{% user_name value.user_id %}</h6>
                                    <p class="mb-0">{% calc_review_count value.user_id %}  friends</p>
                                 </div>
                                 <div class="d-flex align-items-center">
                                    <a href="{% url 'user:confirm-request' value.id %}" class="mr-3 btn rounded" style="background-color: #27b6b6; color: white;">Confirm</a>
                                    <a href="{% url 'user:delete-request' value.id %}" class="mr-3 btn btn-secondary rounded">Delete Request</a>
                                 </div>
                              </li>
                               {% endfor %}

                           </ul>
                        </div>
                     </div>

                  </div>
               </div>
            </div>
         </div>
{% endblock content %}

userprofile/templates/profile/friend_search.html
{% extends 'front/base.html' %}
{% block content %}
{% load static %}
{% load product_tags %}
 <div id="content-page" class="content-page">
            <div class="container">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="iq-card">
                        <div class="iq-card-header d-flex justify-content-between">
                           <div class="iq-header-title">
                              <h4 class="card-title">Search Result</h4>
                           </div>
                        </div>
                        <div class="iq-card-body">
                           <ul class="request-list list-inline m-0 p-0">
                               {% for friend in friends %}
                              <li class="d-flex align-items-center">
                                 <div class="user-img img-fluid"><img src="{% static 'images/user/05.jpg' %}" alt="story-img" class="rounded-circle avatar-40"></div>
                                 <div class="media-support-info ml-3">
                                    <h6>{{friend.username}}</h6>
                                    <p class="mb-0">40 </p>
                                 </div>

                                 <h1> {% friend_find friend.id user.id as fdata %}</h1>

                                  {% if fdata == 'NoData' %}
                                  <form action="{% url 'user:send-friend-request' %}" method="post">
                                      {%  csrf_token %}
                                     <div class="d-flex align-items-center">
                                         <input type="hidden" name="receiver_id" value="{{ friend.id }}">
                                          <button type="submit" class="mr-3 btn rounded" style="background-color: #27b6b6; color: white;">Send Request</button>
                                     </div>
                                 </form>
                                   {% elif fdata == 1 %}
                                        <a href="{% url 'user:cancel-request' friend.id %}" class="mr-3 btn btn-secondary rounded">Cancel sent Request</a>
                                   {% else %}

                                  {% if fdata == 2 %}
                                         <a href="javascript:void();" class="mr-3 btn btn-secondary rounded">Friend</a>
                                  {% endif %}

                                  {% endif %}
                              </li>
                                {% endfor %}
                           </ul>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
{% endblock content %}