social/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
# from django_private_chat import urls as django_private_chat_urls
from django.conf.urls.static import static
from django.conf import settings
from core import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firebase.urls')),
    path('user/', include('userprofile.urls')),
    path('post/', include('post.urls')),
    # url(r'^', include(django_private_chat_urls)),
    url('friendship/', include('userfollow.urls')),
    path('comment/', include('comment.urls')),
    path('group/', include('group.urls')),
    path('product/', include('marketplace.urls')),
    path('web/', include('web.urls')),
    path('blog/', include('blog.urls')),
    path('todo/', include('todo.urls')),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url('notification/', include('notifications.urls', 'notifications')),
    url('chat/', include('chat.urls')),
    url('advertise/', include('advertise.urls')),
    url('tools/', include('tools.urls')),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    path('channel/', include('chanel.urls')),


]
if urlpatterns:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

todo/urls.py
from django.urls import path
from . import views
app_name = "todo"

urlpatterns = [

    path('todo-list/', views.TodoListView.as_view(), name="todo-list"),
    path('add-project/', views.AddTodoView.as_view(), name="add-project"),
    path('update-project/', views.UpdateTodoView.as_view(), name="update-project"),
    path('edit-todo/<int:pk>', views.EditTodoView.as_view(), name="edit-todo"),
    path('delete-todo/<int:pk>', views.DeleteTodoView.as_view(), name="delete-todo"),


]

web/urls.py
from django.urls import path
from . import views
app_name = "web"

urlpatterns = [

]

todo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now


class Todo(models.Model):
    title = models.CharField(max_length=100)
    details = models.TextField()
    date = models.DateTimeField(default=now)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE, editable=False,null=True,blank=True)

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ("title", "details", "date")
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Project name'}),
            'date': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Product date'}),
            'details': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }

todo/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views import View

from .forms import TodoForm
from .models import Todo


class TodoListView(View):

    def get(self, request):
        form = TodoForm()
        item_list = Todo.objects.filter(created_by=request.user.id)
        context = {
            'todos': item_list,
            'form': form
        }
        return render(request, 'todo/index.html', context)


class AddTodoView(View):
    def post(self, request):
        form = TodoForm(request.POST or None)
        if request.method == 'POST':
            if form.is_valid():
                obj = form.save(commit=False)
                obj.created_by_id = request.user.id
                obj.save()
                messages.success(request, "Successfully created")
        return redirect('todo:todo-list')


class UpdateTodoView(View):
    def post(self, request):
        if request.method == 'POST':
            pk = request.POST.get('pk')
            data = Todo.objects.get(pk=pk)
            data.title = request.POST.get('title')
            data.date = request.POST.get('date')
            data.created_by_id = request.user.id
            data.save()
            messages.success(request, "Successfully updated")
        return redirect('todo:todo-list')


class EditTodoView(View):
    def get(self, request, pk):
        data = Todo.objects.get(pk=pk)
        context = {
            'data': data
        }
        return render(request, 'todo/edit.html', context)


class DeleteTodoView(View):
    def get(self, request, pk):
        data = Todo.objects.get(pk=pk)
        data.delete()
        messages.success(request, "Data deleted")
        return redirect('todo:todo-list')

todo/templates/todo/edit.html
{% extends 'front/base.html' %}
{% block content %}
{% load static %}
{% load product_tags %}
<div class="container" style="margin-top: 100px;">
    <h3>Edit</h3>


 <form action="{% url 'todo:update-project' %}" method="post" id="contactform">
        {% csrf_token %}

        <div class="row">
            <input type="hidden" name="pk" value="{{ data.id }}">
            <div class="col">
                <title>Title</title>
                <input type="text" name="title" class="form-control" value="{{ data.title }}">
            </div>

            <div class="col">
                 <input type="date" name="date" class="form-control" required value="{{ data.date }}">
            </div>
        </div>
        <div class="row">
            <div class="col">
                <textarea name="details" id="" class="form-control"  cols="50" rows="3">{{ data.details }}</textarea>
            </div>

        </div>

        <div class="row">

            <input type="hidden" name="user_id" value="{{ user.id }}">

        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-success">Save changes</button>
        </div>
    </form>
</div>

{% endblock content %}

todo/templates/todo/index.html
{% extends 'front/base.html' %}
{% block content %}
{% load static %}
{% load product_tags %}
<style>
    .modal-dialog {
    margin-top: 25%;
}

</style>

<div id="content-page" class="content-page">
    <div class="container relative">
        <div class="row">
            <div class="col-lg-3">
                <div class="add-new-project mt-3 mb-3">
                    <button class="pull-right btn btn-info" data-toggle="modal" data-target="#todoModal">Add Project
                    </button>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="col-md-10">
                    <div class="iq-card">
                        <div class="iq-card-body p-0">
                            <ul class="todo-task-lists m-0 p-0">
                                {% for value in todos %}
                                <li class="d-flex align-items-center p-3">
                                    <div class="user-img img-fluid"><img src="{% static 'images/user/01.jpg' %}"
                                                                         alt="story-img"
                                                                         class="rounded-circle avatar-40"></div>
                                    <div class="media-support-info ml-3">
                                        <h6 class="d-inline-block">{{ value.title }}</h6>
                                        <span class="badge badge-warning ml-3 text-white">{{ value.date }}</span>
                                        <p class="mb-0">by {% user_name value.created_by_id %}</p>
                                    </div>
                                    <div class="iq-card-header-toolbar d-flex align-items-center">
                                        <div class="custom-control custom-checkbox">
                                            <a href="{% url 'todo:edit-todo' value.id %}"><i
                                                    class="fa fa-pencil"></i></a>
                                            <a class="text-danger" onclick="return confirm(' you want to delete?');"
                                               href="{% url 'todo:delete-todo' value.id %}"><i class="fa fa-trash"></i></a>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
</div>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <p {% if message.tags %} class="text-success" {% endif %}> {{ message }} </p>
    {% endfor %}
</ul>
{% endif %}

<div class="modal fade" id="todoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add Project</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'todo:add-project' %}" method="post" id="contactform">
                    {% csrf_token %}

                    <div class="row">

                        <div class="col">
                            <title>{{ form.title.label }}</title>
                            {{ form.title }}
                        </div>

                        <div class="col">
                            {{ form.date }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            {{ form.details }}
                        </div>

                    </div>

                    <div class="row">

                        <input type="hidden" name="user_id" value="{{ user.id }}">

                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Save changes</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

{% endblock content %}