advertise/urls.py
from django.urls import path
from . import views
app_name = "advertise"

urlpatterns = [
    path("ads-list", views.AdsViewListView.as_view(), name="ads-list"),
    path("create-campaign", views.AdsCreateView.as_view(), name="create-campaign"),
    path("update-campaign", views.CampaignUpdateView.as_view(), name="update-campaign"),
    path("edit-campaign/<int:pk>", views.CampaignEditView.as_view(), name="edit-campaign"),
    path("delete-campaign/<int:pk>", views.DeleteCampaignView.as_view(), name="delete-campaign"),

]

social/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
# from django_private_chat import urls as django_private_chat_urls
from django.conf.urls.static import static
from django.conf import settings
from core import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firebase.urls')),
    path('user/', include('userprofile.urls')),
    path('post/', include('post.urls')),
    # url(r'^', include(django_private_chat_urls)),
    url('friendship/', include('userfollow.urls')),
    path('comment/', include('comment.urls')),
    path('group/', include('group.urls')),
    path('product/', include('marketplace.urls')),
    path('web/', include('web.urls')),
    path('blog/', include('blog.urls')),
    path('todo/', include('todo.urls')),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url('notification/', include('notifications.urls', 'notifications')),
    url('chat/', include('chat.urls')),
    url('advertise/', include('advertise.urls')),
    url('tools/', include('tools.urls')),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    path('channel/', include('chanel.urls')),


]
if urlpatterns:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

web/urls.py
from django.urls import path
from . import views
app_name = "web"

urlpatterns = [

]

ads/models.py
from django.db import models

# Create your models here.

advertise/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now
from chanel.models import Channel

GEEKS_CHOICES = (
    ("1", "Active"),
    ("2", "Deactivate"),
)

GENDER_CHOICES = (
    ("1", "Male"),
    ("2", "Female"),
)


class Country(models.Model):
    name = models.CharField(max_length=50, null=True)
    code = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class Advertisement(models.Model):
    header = models.TextField(null=True, blank=True, help_text="Appears on all pages right under the nav bar")
    sidebar = models.TextField(null=True, blank=True, help_text="Appears on the bottom of home sidebar")
    footer = models.TextField(null=True, blank=True, help_text="Appears on the bottom of home footer")
    post = models.TextField(null=True, blank=True, help_text="Appears in posts are loaded")
    status = models.CharField(max_length=5, choices=GEEKS_CHOICES, default=1)


class Campaign(models.Model):
    status = models.CharField(max_length=5, choices=GEEKS_CHOICES, default=1)
    created_at = models.DateTimeField(null=True, blank=True, default=now)
    gender = models.CharField(max_length=5, choices=GENDER_CHOICES, default=0)
    placement = models.TextField(max_length=255, null=True, blank=True)
    bidding = models.IntegerField(null=True, blank=True)
    url = models.CharField(max_length=255, null=True, blank=True)
    page = models.ForeignKey(Channel, on_delete=models.CASCADE,null=True, blank=True )
    audience = models.ForeignKey(Country, on_delete=models.CASCADE,null=True, blank=True )
    start = models.CharField(max_length=255, null=True, blank=True)
    end = models.CharField(max_length=255, null=True, blank=True)
    budget = models.IntegerField(null=True, blank=True)
    company = models.CharField(max_length=255, null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(max_length=255, null=True, blank=True)
    image = models.FileField(null=True, blank=True, upload_to='campaign/')
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True )

    def __str__(self):
        return self.title

advertise/forms.py
from bootstrap_datepicker_plus import DatePickerInput
from django import forms
from .models import Campaign


class CampaignForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CampaignForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Campaign
        fields = ['title', 'company', 'description', 'budget', 'status', 'end', 'gender', 'placement', 'bidding', 'url', 'page', 'audience', 'start', 'image']
        widgets = {
            'start': DatePickerInput(format='%Y-%m-%d'),
            'end': DatePickerInput(format='%Y-%m-%d'),
        }

ads/views.py
from django.shortcuts import render

# Create your views here.

advertise/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from chanel.models import Channel
from django.views.generic import UpdateView, DeleteView

from .models import Country, Campaign
from .forms import CampaignForm


class AdsViewListView(View):
    def get(self, request):
        campaign = Campaign.objects.filter(user=request.user)
        context = {
            'campaigns': campaign
        }
        return render(request, 'ads/list.html', context)


class AdsCreateView(View):
    def get(self, request):
        channel = Channel.objects.filter(user_id=request.user.id)
        form = CampaignForm()
        county = Country.objects.all()
        context = {
            'channel': channel,
            'countries': county,
            'form': form
        }

        return render(request, 'ads/create.html', context)

    def post(self, request):
        form = CampaignForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = self.request.user
            obj.image = form.cleaned_data['image']
            obj.save()
            context = {
                'form': form
            }
            messages.success(request, 'Form submission successful')
            return render(request, 'ads/create.html', context)
        else:
            messages.error(request, "Error")

        context = {
            'form': form
        }
        return render(request, 'ads/create.html', context)


class CampaignEditView(View):
    def get(self, request, pk):
        data = Campaign.objects.get(pk=pk)
        form = CampaignForm()
        county = Country.objects.all()
        context = {
            'form': form,
            'data': data,
            'countries': county,
        }
        return render(request, 'ads/update.html', context)


class CampaignUpdateView(View):
    def get(self, request, pk):
        title =request.POST.get('title')
        gender =request.POST.get('gender')
        placement =request.POST.get('placement')
        bidding =request.POST.get('bidding')
        url =request.POST.get('url')
        page =request.POST.get('page')
        audience =request.POST.get('audience')
        start =request.POST.get('start')
        end =request.POST.get('end')
        budget =request.POST.get('budget')
        company =request.POST.get('company')
        description =request.POST.get('description')
        image =request.POST.get('image')

        data = Campaign.objects.get(pk=pk)
        data.tile = title
        data.gender = gender
        data.placement = placement
        data.bidding = bidding
        data.url = url
        data.page = page
        data.audience = audience
        data.start = start
        data.end = end
        data.budget = budget
        data.company = company
        data.description = description
        data.image = image
        data.save()

        return redirect('advertise:ads-list')


class DeleteCampaignView(View):
    def get(self, request, pk):
        data = Campaign.objects.get(pk=pk)
        data.delete()
        return reverse_lazy('advertise:ads-list')

advertise/templates/ads/create.html
{% extends 'front/base.html' %}
{% load static %}
{% block title %}Konetos | Create Campaign {% endblock %}
{% block content %}

{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}

<div id="content-page" class="content-page">
            <div class="container">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="iq-card">
                        <div class="iq-card-body">
                             {% if form.errors %}
                                <!-- Error messaging -->
                                <div id="errors">
                                    <div class="inner">
                                        <p>There were some errors in the information you entered. Please correct the following:</p>
                                        <ul>
                                            {% for field in form %}
                                                {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                <!-- /Error messaging -->
                            {% endif %}
                           <form method="post" action="{% url 'advertise:create-campaign' %}" enctype="multipart/form-data">
                               {% csrf_token %}
                               <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.title.label }}</label>
                                 {{ form.title }}
                              </div>

                              <div class="form-group">
                                 <label for="exampleInputText1">{{ form.gender.label }}</label>
                                 {{ form.gender }}
                              </div>

                               <div class="form-group">
                                 <label for="exampleInputText2">{{ form.placement.label }}</label>
                                 {{ form.placement }}
                              </div>

                               <div class="form-group">
                                 <label for="exampleInputText3">{{ form.bidding.label }}</label>
                                 {{ form.bidding }}
                              </div>

                              <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.url.label }}</label>
                                 {{ form.url }}
                              </div>

                              <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.page.label }}</label>
                                 {{ form.page }}
                              </div>
                              <div class="form-group">
                                 <label for="exampleInputNumber1">Audience </label>
                                 <select class="form-control form-control-lg w-100" id="audience" name="audience">
                                     {% for country in countries %}
                                    <option value="{{ country.id }}">{{ country.name }}</option>
                                   {% endfor %}
                                 </select>
                              </div>
                              <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.start.label }}</label>
                                 {{ form.start }}
                              </div>

                              <div class="form-group">
                                  <label for="exampleInputNumber1">{{ form.end.label }}</label>
                                 {{ form.end }}
                              </div>
                              <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.budget.label }}</label>
                                 {{ form.budget }}
                              </div>
                              <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.company.label }}</label>
                                 {{ form.company }}
                              </div>
                               <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.location.label }}</label>
                                 {{ form.location }}
                              </div>
                               <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.status.label }}</label>
                                 {{ form.status }}
                              </div>
                              <div class="form-group">
                                 <label for="exampleFormControlTextarea1">{{ form.description.label }}</label>
                                 {{ form.description }}
                              </div>
                               <div class="form-group">
                                 <label for="exampleFormControlTextarea1">{{ form.image.label }}</label>
                                   {{ form.image }}
                              </div>
                               <br>
                              <button type="submit" class="btn btn-lg" style="background-color: #27b6b6; color: white;">Submit</button>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>

{% endblock content %}

advertise/templates/ads/list.html
{% extends 'front/base.html' %}
{% load static %}
{% block title %}Konetos | Ads {% endblock %}
{% block content %}
{% load product_tags %}

 <div id="content-page" class="content-page">
            <div class="container">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="iq-card">
                        <div class="iq-card-header d-flex justify-content-between">
                           <div class="iq-header-title">

                              <a class="btn btn-success pull-right" href="{% url 'advertise:create-campaign' %}">Create Campaign</a>
                           </div>
                        </div>
                        <div class="iq-card-body">
                           <div class="table-responsive">
                              <table id="datatable" class="table table-striped table-bordered" >
                                 <thead>
                                    <tr>
                                       <th>Name</th>
                                       <th>Company</th>
                                       <th>Budget</th>
                                       <th>Audience</th>
                                       <th>Start date</th>
                                       <th>End Date</th>
                                       <th>Action</th>
                                    </tr>
                                 </thead>
                                 <tbody>
                                 {% for cam in campaigns %}
                                    <tr>
                                       <td>{{ cam.title }}</td>
                                       <td>{{ cam.company }}</td>
                                       <td>{{ cam.budget }}</td>
                                       <td>{{ cam.audience }}</td>
                                       <td>{{ cam.start }}</td>
                                       <td>{{ cam.end }}</td>
                                       <td>
                                          <a href="{% url 'advertise:edit-campaign' cam.id %}"><i
                                                    class="fa fa-pencil"></i></a>
                                            <a class="text-danger" onclick="return confirm(' you want to delete?');"
                                               href="{% url 'advertise:delete-campaign' cam.id %}"><i class="fa fa-trash"></i></a>
                                       </td>
                                    </tr>
                                 {% endfor %}
                                 </tbody>
                                 <tfoot>
                                    <tr>
                                       <th>Name</th>
                                       <th>Company</th>
                                       <th>Budget</th>
                                       <th>Audience</th>
                                       <th>Start date</th>
                                       <th>End Date</th>
                                       <th>Action</th>
                                    </tr>
                                 </tfoot>
                              </table>
                           </div>
                        </div>
                     </div>
                  </div>

               </div>
            </div>
         </div>
{% endblock content %}

advertise/templates/ads/update.html
{% extends 'front/base.html' %}
{% load static %}
{% block title %}Konetos | Create Campaign {% endblock %}
{% block content %}

{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}

<div id="content-page" class="content-page">
            <div class="container">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="iq-card">
                        <div class="iq-card-body">
                             {% if form.errors %}
                                <!-- Error messaging -->
                                <div id="errors">
                                    <div class="inner">
                                        <p>There were some errors in the information you entered. Please correct the following:</p>
                                        <ul>
                                            {% for field in form %}
                                                {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                <!-- /Error messaging -->
                            {% endif %}
                           <form action="{% url 'advertise:update-campaign' %}" method="post" enctype="multipart/form-data">
                               {% csrf_token %}
                               <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.title.label }}</label>
                                   <input type="text" value="{{data.title}}" name="title"  class="form-control">
                              </div>

                              <div class="form-group">
                                 <label for="exampleInputText1">{{ form.gender.label }}</label>
                                 {{ form.gender }}
                              </div>

                               <div class="form-group">
                                 <label for="exampleInputText2">{{ form.placement.label }}</label>
                                   <textarea class="form-control" name="placement" id="" cols="30" rows="10">{{data.placement}}</textarea>
                              </div>

                               <div class="form-group">
                                 <label for="exampleInputText3">{{ form.bidding.label }}</label>
                                   <input type="number" class="form-control" name="bidding" value="{{data.bidding}}">
                              </div>

                              <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.url.label }}</label>
                                 <input type="url" class="form-control" name="url" value="{{data.url}}">
                              </div>

                              <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.page.label }}</label>
                                 {{ form.page }}
                              </div>
                              <div class="form-group">
                                 <label for="exampleInputNumber1">Audience </label>

                                   {{ form.audience }}
                              </div>
                              <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.start.label }}</label>
                                  <input type="start" class="form-control" name="start" value="{{data.start}}">
                              </div>

                              <div class="form-group">
                                  <label for="exampleInputNumber1">{{ form.end.label }}</label>
                                 <input type="end" class="form-control" name="end" value="{{data.end}}">
                              </div>
                              <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.budget.label }}</label>
                                 <input type="budget" class="form-control" name="budget" value="{{data.budget}}">
                              </div>
                              <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.company.label }}</label>
                                 <input type="company" class="form-control" name="company" value="{{data.company}}">
                              </div>

                               <div class="form-group">
                                 <label for="exampleInputNumber1">{{ form.status.label }}</label>
                                 <input type="status" class="form-control" name="status" value="{{data.status}}">
                              </div>
                              <div class="form-group">
                                 <label for="exampleFormControlTextarea1">{{ form.description.label }}</label>
                                  <textarea name="description" class="form-control" cols="30" rows="10">{{ data.description }}</textarea>
                              </div>
                               <div class="form-group">
                                 <label for="exampleFormControlTextarea1">{{ form.image.label }}</label>
                                   <input type="file" name="image" class="form-control">
                              </div>
                               <br>
                              <button type="submit" class="btn btn-lg" style="background-color: #27b6b6; color: white;">Submit</button>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>

{% endblock content %}